### ISSUE TITLE
Logotype

### ISSUE THREAD

**Issue by nunojesus** [cornerman/chameleon#2]
Hi, concrats for your project!
Do you have a logotype? If you need one I can do it for free, I love to contribute to opensource projects, so if you want one just say it.

Cheers!

**Comment by cornerman** [comment]
Hi, that sounds awesome! I would love to have a logo :)

**Comment by cornerman** [comment]
Hmm. I would need to think about it. But if you have an idea in mind, please feel free to just try something out!

**Comment by nunojesus** [comment]
Hello, here is my first design that I create for your project, it´s a rounded Chameleon, that is almost a C letter. The first one I used the colors that are in the reade.me file. I hope you like it, if you want to make changes just say it, also if you dont like it I can make you a new design.

Greetings!
Nuno Jesus
![camaleao](https://user-images.githubusercontent.com/34600369/41196870-20aba568-6c43-11e8-8585-4530d75b99fd.png)

**Comment by cornerman** [comment]
Cool, I really like this design! Especially having two or three colors mixed like the top-left and bottom-right one looks nice and underlines the nature of this library. For the colors, can we try out mixing blue-green or blue-green-red?

Out of interest: Which font are using?

**Comment by nunojesus** [comment]
I can try that colors, the font I used is Righteous, I can use the one you have in the readme file, or other one that you like. Greetings!

**Comment by cornerman** [comment]
Great! Please keep the font, the "e" looks so happy and relaxed :)

**Comment by nunojesus** [comment]
Im happy that you like it, I will try to make the color changes that you request and show them to you. Cheers!

**Comment by nunojesus** [comment]
See if you like one of this, my favourite is the 1st the green and blue.

Cheers!

![camaleao2](https://user-images.githubusercontent.com/34600369/41200968-e4646b6c-6ca6-11e8-833c-903e68fc6018.png)

**Comment by cornerman** [comment]
@nunojesus Did you maybe open the [PR](https://github.com/supersimple/chameleon/pull/16) in the wrong repo?

**Comment by nunojesus** [comment]
Sorry, I will open the PR in the right repo.

Greetings!
Nuno Jesus

**Comment by cornerman** [comment]
Great, no worries!

**Comment by cornerman** [comment]
Fixed with #3
